routes/web.php
<?php



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::group(['middleware' => 'auth'], function () {
   
    Route::resource('blog', 'BlogController');
    Route::resource('profile', 'ProfileController');
    
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravelista\Comments\Commentable;

class blog extends Model
{
    protected $table = 'blogs';
    protected $fillable = ['judul','isi','image'];
    use Commentable;
    public function user(){
        return $this->belongsTo('App\User');
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\blog;
use Illuminate\Http\Request;
use Auth;
use Alert;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {

        \Cloudinary::config([

            "cloud_name" => "dbpyiy8on",
            "api_key" => "971919886571495",
            "api_secret" => "MCv9__sqfovBlFEAYV6Dtdeh6oA"

        ]);

    }

    public function index()
    {
        $postingan = Blog::all();

        return view('blog')->with(['postingan' => $postingan]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blog.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $blog = new Blog;
        $data = $request->all();
        if ($files = $request->file('gambar')) {
            $destinationPath = 'gambar/';
            $profileImage = date('YmdHis') ;
            //. "." . $files->getClientOriginalExtension()
            // $files->move($destinationPath, $profileImage);

            \Cloudinary\Uploader::upload($files, ["public_id" => $profileImage]);

            $blog->image = $profileImage;
        }
        $blog->judul = $request->judul;
        $blog->isi = $request->isi;
        $blog->user_id = Auth::user()->id;
        $blog->save();

        Alert::success('success', 'Post was Created!');

        return redirect(route('blog.index'));
    }

    /** 
     * Display the specified resource.
     *
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::find($id);
        $blog->image=\Cloudinary::cloudinary_url($blog->image);
        return view('blog.show')->with(['blog' => $blog]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::find($id);
        return view('blog.edit')->with(['blog' => $blog]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $blog = Blog::find($id);

        // $blog = new Blog;
        $blog->judul = $request->judul;
        $blog->isi = $request->isi;
       
        $blog->user_id = Auth::user()->id;

        $data = $request->all();
        if ($request->hasfile('gambar')) {
            $files = $request->file('gambar');
            // $destinationPath = '';
            $profileImage = date('YmdHis') ;
            // . "." . $files->getClientOriginalExtension();
            // $files->move('gambar/', $profileImage);

            \Cloudinary\Uploader::upload($files, ["public_id" => $profileImage]);
            $blog->image = $profileImage;
        }
     
        $blog->save();

        return redirect('blog')->with('blog', $blog);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $item =Blog::find($id);
       $item->delete();
       return redirect('blog');
    }
}

resources/views/blog/edit.blade.php
@extends('layouts.app')
@section('content')
     <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h4 class="m-0 text-dark">Edit Postingan</h4>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">



                        <form class="container" action="/blog/{{$blog->id}}" method="POST" enctype="multipart/form-data">
                          {{csrf_field()}}
                            {{ method_field('PUT') }}
                              <div class="form-group">
                                <label for="exampleFormControlInput1">Judul</label>
                                <input type="text" class="form-control" id="exampleFormControlInput1" name="judul" value="{{$blog->judul}}">
                              </div>
                              <div class="form-group">
                                <label for="exampleFormControlTextarea1">Isi</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Isi Postingan" name="isi">{{$blog->isi}}</textarea>
                              </div>
                              <div class="input-group">
                                <div class="custom-file">
                                  <input type="file" class="custom-file-input" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" name="gambar">
                                  <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                  <button class="btn btn-outline-secondary" type="submit" id="inputGroupFileAddon04">Submit</button>
                                </div>
                              </div>
                          
                            </form>




                        {{--  <form action="/blog/{{$blog->id}}" method="POST">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                              <label for="exampleInputEmail1">Judul Pertanyaan</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" name="judul" value="{{$blog->judul}}">
                            </div>
                            <div class="form-group">
                              <label for="exampleInputPassword1">Isi</label>
                              <textarea class="form-control" id="exampleInputPassword1" name="isi">{{$blog->isi}} </textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Edit</button>
                          </form>  --}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/blog/editprofil.blade.php
@extends('layouts.app')
<div class="container">
    <div class="row">
        <div class="col-md mt-4">
<div class="card mt-5">
<div class="card-body">
    <form class="container" action="/profile/{{$profile->id}}" method="POST" enctype="multipart/form-data">
        {{csrf_field()}}
        {{method_field('PUT')}}

        <div class="form-group">
            <label for="inputNama">Nama</label>
            <input type="text" class="form-control" id="inputNama" placeholder="Nama Lengkap" value="{{$profile->name}}" name="name">
        </div>
        <div class="form-group">
            <label for="inputBio"> Bio </label> 
            <input class="form-control" type="text" placeholder="Bio" value="{{$profile->bio}}" name="bio">
        </div>
        <div class="form-group">
          <label for="inputAddress">Alamat</label>
          <input type="text" class="form-control" id="inputAddress" placeholder="Alamat" value="{{$profile->alamat}}" name="alamat">
        </div>
        <div class="form-group">
          <label for="inputAgama">Agama</label>
          <input type="text" class="form-control" id="inputAgama" placeholder="Agama" value="{{$profile->agama}}" name="agama">
        </div>
        <div class="form-group">
            <label for="inputStatus">Status</label>
            <input type="text" class="form-control" id="inputStatus" placeholder="Status" value="{{$profile->status}}" name="status">
          </div>


          {{--  <select class="form-control" value={{$profile->jenis_kelamin}} name="jenis_kelamin">
            <option value="Laki-laki">Laki-laki</option>
            <option value="Perempuan">Perempuan</option>
          </select>  --}}

            <button type="submit" class="btn btn-outline-secondary btn-lg btn-block mt-4">Edit</button>
        </form>
    </div>
</div>
</div>
</div>
</div>
</div>

resources/views/blog/form.blade.php
@extends('layouts.app')
@section('content')
    

<form class="container mt-5" action="{{ route('blog.store') }}" method="POST" enctype="multipart/form-data">
  @csrf
    <div class="form-group">
      <label for="exampleFormControlInput1">Judul</label>
      <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Judul Postingan" name="judul">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Isi</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Isi Postingan" name="isi"></textarea>
    </div>
    <div class="input-group">
      <div class="custom-file">
        <input type="file" class="custom-file-input" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" name="gambar">
        <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
      </div>
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Submit</button>
      </div>
    </div>

  </form>
 
@endsection

resources/views/blog/profile.blade.php
@extends('layouts.app')
@section('content')
    
{{--  Bagian foto profil  --}}
<div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
        
        <img src="/frontend/images/people.png" width="200" class="Rounded-circle">
        <h1 class="display-4" name="name">{{ Auth::user()->name }}</h1>
        <p class="lead"> {{ Auth::user()->bio }} </p>
        
     </div>
  </div>

{{--  Menampilkan postingan pertanyaan  --}}
<div class="container">
    <div class="row row-cols-2">
      <div class="col-4">
        
        <ul class="list-group">
            <li class="list-group-item text-white bg-dark text-center">A  B  O  U  T</li>
            <li class="list-group-item">Status : {{ Auth::user()->status }}</li>
            <li class="list-group-item">Agama : {{ Auth::user()->agama }}</li>
            <li class="list-group-item">Alamat : {{ Auth::user()->alamat }} </li>
            <li class="list-group-item">
                
                  <a href="/profile/{{Auth::user()->id}}/edit" class="text-dark btn btn-outline-secondary btn-lg btn-block"> C H A N G E </a>
                
            </li>
          </ul>
      
    </div>
    <div class="col-8">
          
    @foreach ($blog as $item)
        
    <div class="card mt-1 mb-3" style="width: 40rem;">
            <div class="row">
              <div class="col-md-8">
                <div class="card-body">
        
                  <a href="blog/{{$item->id}}" style="text-decoration:none" class="text-dark">
                 
                    <h5 class="card-title">{{$item->judul}}</h5>
                  
                  </a>
        
                
                  <p class="card-text">{{$item->isi}}</p>
                  <img src="https://res.cloudinary.com/dbpyiy8on/image/upload/{{$item->image}}" class="img-thumbnail" style="max-width: 600px">
                  <p class="card-text"><small class="text-muted">{{$item->created_at}}</small></p>
                  <button type="button" class="btn btn-primary btn-sm"><a href="/blog/{{$item->id}}" style="text-decoration:none" class="text-light"> Komentar </a> </button>
                </div>
              </div>
            </div>
          </div>
    
    
    @endforeach    
    
        
        </div>
    </div>
</div>

@endsection

resources/views/blog/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
   
                    <div class="card mt-5" style="width: 40rem;">
                    <div class="row no-gutters">
                      <div class="col">
                        <div class="card-body">
                         
                          <h5 class="card-title">{{$blog->judul}}</h5>
                       
                          <p class="card-text">{{$blog->isi}}</p>
                          <img src="{{$blog->image}}" class="img-thumbnail" >
                          <p class="card-text"><small class="text-muted">{{$blog->created_at}}</small></p>
                          
                          @if($blog->user->id == Auth::user()->id)
                          <div class="d-flex">
                          <button type="button" class="btn btn-light"> <a href="/blog/{{$blog->id}}/edit" class="text-dark"> Edit </a> </button>                     
                          <form action="{{route('blog.destroy',[$blog->id])}}" method="POST">
                            {{csrf_field()}}
                            {{method_field('DELETE')}}
                          {{--  < type="submit" class="btn btn-danger btn-sm mt-2">  --}}
                            <input type="submit" value="Delete"  class="btn btn-outline-danger">
              
                          </form>
                          </div>
                          @endif
                          

                      <div class="mt-2">
                        @comments(['model' => $blog])
                      </div>



                        </div>
                      </div>
                    </div>
                  </div>
                </div>
@endsection